openapi: 3.0.0
info:
  title: CCS Notification Service
  description: This CCS Conversations Service API.
  termsOfService: 'http://api.crowncommercial.gov.uk/terms/'
  contact:
    email: apiteam@crowncommercial.gov.uk
  license:
    name: Open Government Licence 3.0
    url: 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'
  version: 1.0.5
servers:
  - url: /
tags:
  - name: NotificationService
    description: 'Everything about SecurityService '
    externalDocs:
      description: Find out more
      url: 'http://apis.crowncommercial.gov.uk'
paths:

  /notifications/:     
    get:
      description: Get supplier ID's and names for that have responded to the given question.
      tags:
        - Notifications Service
      summary: Retrieve Event Document Response
      operationId: getNotifications
      responses:
        '200':
          description: ok
          content:
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '401':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/429TooManyRequests'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'
        '502':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/502BadGateway'

    post:
      description: Creates a new Event for the Procurement Project.
      tags:
         - Notifications Service
      operationId: createNotification
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: ok
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/parameters/NotificationId'
        '401':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/429TooManyRequests'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'
        '502':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/502BadGateway'
      
            
  /notifications/{notification-id}:     
    parameters:
      - $ref: '#/components/parameters/NotificationId'
    patch:
      description: Allows the recipient of the notification to update its status.
      tags:
        - Notifications Service 
      summary: Retrieve Event Document Response
      operationId: updateNotification
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: ok
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/429TooManyRequests'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'
        '502':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/502BadGateway'

            
components:
  parameters:
    NotificationId:
      name: notification-id
      in: path
      required: true
      description: Notification ID
      schema:
        $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Schema.yaml#/components/schemas/GenericId'
           
  schemas:
    Notification:
      title: Notification
      description: >-
        Details of a Notification (Internal, Email, SMS, ....)
      type: object
      properties:
        Channel:
          type: string
          nullable: true
          enum:
          - Email
          - SMS
          - Letter
          - Internal
        Template:
          type: string
          nullable: true
        TemplateData:
          nullable: true
          type: array
          items:
            type: object
            properties:
                key:
                  type: string
                value:
                    type: string
        SourceSystem:
          type: string
          readOnly: true
        NotificationText:
          type: string
          nullable: false
        EffectiveFrom:
          type: string
          format: date
          nullable: false
        EffectiveTo:
          type: string
          format: date
          nullable: true
        State:
          type: string
          readOnly: true
          enum:
          - Accepted
          - Sent
          - Read
          - Actioned

          
    NotificationSummary:
      title: Notification Summary
      description: >-
        Summary details of a Notification (Internal, Email, SMS, ....)
      type: object
      properties:
        Name:
          type: string
          nullable: true
        Type:
          type: string
          nullable: true